import { describe, expect, it } from 'vitest';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { parse } from 'yaml';

const SCHEMA_SYNC_PATH = path.resolve(
  __dirname,
  '../.github/workflows/directus-schema-sync.yml',
);

type Step = {
  id?: string;
  run?: string;
  uses?: string;
  with?: Record<string, unknown>;
};
type Workflow = { jobs: Record<string, { steps: Step[] }> };

function loadWorkflow(): Workflow {
  return parse(readFileSync(SCHEMA_SYNC_PATH, 'utf-8'));
}

function findStep(workflow: Workflow, predicate: (s: Step) => boolean): Step {
  const step = Object.values(workflow.jobs)
    .flatMap((j) => j.steps)
    .find(predicate);
  expect(step).toBeDefined();
  return step as Step;
}

// Requirement 3.6, 4.2: ConfigMaps generated by the schema-sync workflow must be
// well-formed and must faithfully embed the real snapshot.yaml content, for both
// prod and staging. This runs the *actual* `kubectl create configmap` command
// lifted verbatim from the workflow (client-side only — no live cluster needed).
describe('generated manifests — schema ConfigMap (3.2, 4.1, 4.2)', () => {
  function extractConfigmapScript(): string {
    const workflow = loadWorkflow();
    const step = findStep(workflow, (s) =>
      Boolean(s.run?.includes('kubectl create configmap directus-schema')),
    );
    return step.run as string;
  }

  it('produces a valid ConfigMap for prod and staging containing the snapshot content', () => {
    const dir = mkdtempSync(path.join(tmpdir(), 'configmap-gen-'));
    mkdirSync(path.join(dir, 'directus/schema'), { recursive: true });
    mkdirSync(path.join(dir, 'infra/gitops/manifests/prod/directus'), {
      recursive: true,
    });
    mkdirSync(path.join(dir, 'infra/gitops/manifests/staging/directus'), {
      recursive: true,
    });
    const snapshotContent = 'collections:\n  - collection: test\n';
    writeFileSync(path.join(dir, 'directus/schema/snapshot.yaml'), snapshotContent);

    execFileSync('bash', ['-c', extractConfigmapScript()], {
      cwd: dir,
      env: process.env,
      encoding: 'utf-8',
    });

    for (const env of ['prod', 'staging']) {
      const generated = readFileSync(
        path.join(dir, `infra/gitops/manifests/${env}/directus/schema-configmap.yaml`),
        'utf-8',
      );
      const manifest = parse(generated);
      expect(manifest.apiVersion).toBe('v1');
      expect(manifest.kind).toBe('ConfigMap');
      expect(manifest.metadata.name).toBe('directus-schema');
      expect(manifest.metadata.namespace).toBe(env);
      expect(manifest.data['snapshot.yaml']).toBe(snapshotContent);
    }
  });

  it('skips the migrations ConfigMap when no migration files exist', () => {
    const dir = mkdtempSync(path.join(tmpdir(), 'configmap-gen-'));
    mkdirSync(path.join(dir, 'directus/schema'), { recursive: true });
    mkdirSync(path.join(dir, 'infra/gitops/manifests/prod/directus'), {
      recursive: true,
    });
    mkdirSync(path.join(dir, 'infra/gitops/manifests/staging/directus'), {
      recursive: true,
    });
    writeFileSync(path.join(dir, 'directus/schema/snapshot.yaml'), 'collections: []\n');

    execFileSync('bash', ['-c', extractConfigmapScript()], {
      cwd: dir,
      env: process.env,
      encoding: 'utf-8',
    });

    expect(() =>
      readFileSync(
        path.join(dir, 'infra/gitops/manifests/prod/directus/migrations-configmap.yaml'),
        'utf-8',
      ),
    ).toThrow();
  });
});

// Requirement 3.6: the GitHub App must be the least-privilege token described in the
// design — scoped to aramakisai-infra only, with exactly contents:write + pull-requests:write.
describe('generated manifests — GitHub App least privilege (3.6, 4.2)', () => {
  it('scopes the installation token to aramakisai-infra with no other repos', () => {
    const workflow = loadWorkflow();
    const tokenStep = findStep(workflow, (s) =>
      s.uses?.startsWith('actions/create-github-app-token') === true,
    );
    expect(tokenStep.with?.owner).toBe('aramakisai');
    expect(tokenStep.with?.repositories).toBe('aramakisai-infra');
  });

  it('grants exactly contents:write and pull-requests:write, nothing broader', () => {
    const workflow = loadWorkflow();
    const tokenStep = findStep(workflow, (s) =>
      s.uses?.startsWith('actions/create-github-app-token') === true,
    );
    const permissionKeys = Object.keys(tokenStep.with ?? {}).filter((k) =>
      k.startsWith('permission-'),
    );
    expect(permissionKeys.sort()).toEqual(
      ['permission-contents', 'permission-pull-requests'].sort(),
    );
    expect(tokenStep.with?.['permission-contents']).toBe('write');
    expect(tokenStep.with?.['permission-pull-requests']).toBe('write');
  });
});
