/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    announcements: Announcement;
    topics: Topic;
    pages: Page;
    sponsors: Sponsor;
    faq_items: FaqItem;
    map_areas: MapArea;
    stages: Stage;
    time_slots: TimeSlot;
    performance_slots: PerformanceSlot;
    student_exhibitions: StudentExhibition;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    student_exhibitions: {
      performance_slots: 'performance_slots';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    topics: TopicsSelect<false> | TopicsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    faq_items: FaqItemsSelect<false> | FaqItemsSelect<true>;
    map_areas: MapAreasSelect<false> | MapAreasSelect<true>;
    stages: StagesSelect<false> | StagesSelect<true>;
    time_slots: TimeSlotsSelect<false> | TimeSlotsSelect<true>;
    performance_slots: PerformanceSlotsSelect<false> | PerformanceSlotsSelect<true>;
    student_exhibitions: StudentExhibitionsSelect<false> | StudentExhibitionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    festival_meta: FestivalMeta;
    page_home: PageHome;
  };
  globalsSelect: {
    festival_meta: FestivalMetaSelect<false> | FestivalMetaSelect<true>;
    page_home: PageHomeSelect<false> | PageHomeSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Authentik の sub。OIDC ログイン時に設定される
   */
  authentik_sub?: string | null;
  /**
   * ロールはコード上の定義 (CMS_ROLES) からのみ決まる
   */
  role: 'executive' | 'student_exhibitor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  title: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  body_html?: string | null;
  /**
   * 公開日時 (未設定は非公開)
   */
  published_at?: string | null;
  /**
   * 複数添付ファイル
   */
  attachments?: (number | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics".
 */
export interface Topic {
  id: number;
  title: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  body_html?: string | null;
  /**
   * サムネイル画像
   */
  image?: (number | null) | Media;
  /**
   * 公開日時 (未設定は非公開)
   */
  published_at?: string | null;
  /**
   * PDF 添付 (デジタルパンフ等)
   */
  attachment?: (number | null) | Media;
  /**
   * 表示順
   */
  sort?: number | null;
  /**
   * 複数添付ファイル
   */
  attachments?: (number | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * ページ識別子 (URLパス相当, UNIQUE)
   */
  slug: string;
  /**
   * ページ見出し(h1)および<title>タグに使用
   */
  title: string;
  /**
   * 本文
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  content_html?: string | null;
  /**
   * 埋め込みURL (地図・フォーム等のiframe embed)
   */
  embed_url?: string | null;
  /**
   * embed_urlのiframe高さ(px)。未指定時は16:9のデフォルト比率
   */
  embed_height?: number | null;
  /**
   * 表示順
   */
  sort?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  type: 'ad' | 'sponsor' | 'food_truck' | 'other';
  name: string;
  /**
   * ロゴ画像
   */
  logo?: (number | null) | Media;
  /**
   * Webサイト URL
   */
  url?: string | null;
  /**
   * 説明・応援メッセージ
   */
  description?: string | null;
  /**
   * 業種タグ (地元協賛のみ)
   */
  business_category?: string | null;
  /**
   * 住所 (地元協賛のみ)
   */
  address?: string | null;
  /**
   * 協賛ランク (広告協賛のみ)
   */
  tier?: ('platinum' | 'gold' | 'silver' | 'bronze') | null;
  /**
   * マップ配置エリア (広告協賛はNULL)
   */
  area_id?: (number | null) | MapArea;
  /**
   * エリア内ブース番号 (area_id+booth_number UNIQUE)
   */
  booth_number?: number | null;
  /**
   * マップ表示ラベル
   */
  booth_label?: string | null;
  /**
   * 表示順
   */
  sort?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "map_areas".
 */
export interface MapArea {
  id: number;
  /**
   * 表示名 (例: "Aゾーン")
   */
  name: string;
  /**
   * GeoJSON Polygon
   */
  geometry:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 表示順
   */
  sort?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_items".
 */
export interface FaqItem {
  id: number;
  question: string;
  answer: string;
  /**
   * 表示順
   */
  sort?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stages".
 */
export interface Stage {
  id: number;
  /**
   * ステージ名
   */
  name: string;
  /**
   * 出演場所エリア (OSM Polygon)
   */
  area_id?: (number | null) | MapArea;
  /**
   * 表示順
   */
  sort?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "time_slots".
 */
export interface TimeSlot {
  id: number;
  /**
   * 表示ラベル
   */
  label: string;
  /**
   * 開始時刻
   */
  start_at: string;
  /**
   * 終了時刻
   */
  end_at: string;
  /**
   * 時系列順
   */
  sort?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "performance_slots".
 */
export interface PerformanceSlot {
  id: number;
  /**
   * ステージ (NOT NULL)
   */
  stage_id: number | Stage;
  /**
   * タイムスロット (NOT NULL)
   */
  time_slot_id: number | TimeSlot;
  /**
   * 団体 (NULL可。団体なし出演はtitleを使用)
   */
  exhibition_id?: (number | null) | StudentExhibition;
  /**
   * 表示名 (exhibition_idがNULLの場合必須)
   */
  title?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student_exhibitions".
 */
export interface StudentExhibition {
  id: number;
  owner: number | User;
  status: 'published' | 'draft';
  /**
   * 企画名。団体名は organization_name を参照
   */
  name: string;
  /**
   * 学生団体・サークル名
   */
  organization_name: string;
  /**
   * 最大 2 つまで選択する
   */
  category: ('stage' | 'exhibit' | 'vendor' | 'other')[];
  /**
   * ステージ出演枠 (実行委員が割り当てる。閲覧のみ)
   */
  performance_slots?: {
    docs?: (number | PerformanceSlot)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * マップ配置エリア (NULL=マップ非掲載)。展示・出店のみ使用
   */
  area_id?: (number | null) | MapArea;
  /**
   * エリア内ブース番号 (area_id+booth_number UNIQUE)。展示・出店のみ使用
   */
  booth_number?: number | null;
  /**
   * マップ表示ラベル。展示・出店のみ使用
   */
  booth_label?: string | null;
  /**
   * 一覧表示用短文
   */
  description?: string | null;
  /**
   * 公式サイト・SNS 等のリンク
   */
  links?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 最大 5 枚まで
   */
  images?: (number | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'topics';
        value: number | Topic;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null)
    | ({
        relationTo: 'faq_items';
        value: number | FaqItem;
      } | null)
    | ({
        relationTo: 'map_areas';
        value: number | MapArea;
      } | null)
    | ({
        relationTo: 'stages';
        value: number | Stage;
      } | null)
    | ({
        relationTo: 'time_slots';
        value: number | TimeSlot;
      } | null)
    | ({
        relationTo: 'performance_slots';
        value: number | PerformanceSlot;
      } | null)
    | ({
        relationTo: 'student_exhibitions';
        value: number | StudentExhibition;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  authentik_sub?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  body_html?: T;
  published_at?: T;
  attachments?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics_select".
 */
export interface TopicsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  body_html?: T;
  image?: T;
  published_at?: T;
  attachment?: T;
  sort?: T;
  attachments?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  content?: T;
  content_html?: T;
  embed_url?: T;
  embed_height?: T;
  sort?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  type?: T;
  name?: T;
  logo?: T;
  url?: T;
  description?: T;
  business_category?: T;
  address?: T;
  tier?: T;
  area_id?: T;
  booth_number?: T;
  booth_label?: T;
  sort?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_items_select".
 */
export interface FaqItemsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  sort?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "map_areas_select".
 */
export interface MapAreasSelect<T extends boolean = true> {
  name?: T;
  geometry?: T;
  sort?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stages_select".
 */
export interface StagesSelect<T extends boolean = true> {
  name?: T;
  area_id?: T;
  sort?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "time_slots_select".
 */
export interface TimeSlotsSelect<T extends boolean = true> {
  label?: T;
  start_at?: T;
  end_at?: T;
  sort?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "performance_slots_select".
 */
export interface PerformanceSlotsSelect<T extends boolean = true> {
  stage_id?: T;
  time_slot_id?: T;
  exhibition_id?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student_exhibitions_select".
 */
export interface StudentExhibitionsSelect<T extends boolean = true> {
  owner?: T;
  status?: T;
  name?: T;
  organization_name?: T;
  category?: T;
  performance_slots?: T;
  area_id?: T;
  booth_number?: T;
  booth_label?: T;
  description?: T;
  links?: T;
  images?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "festival_meta".
 */
export interface FestivalMeta {
  id: number;
  /**
   * 祭名
   */
  name: string;
  /**
   * 日ごと開催時間 [{label, open, close}]
   */
  event_days?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 駐車場マップ画像
   */
  parking_map?: (number | null) | Media;
  /**
   * SNSリンク一覧
   */
  sns_links?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 祭概要 (WYSIWYG)
   */
  overview?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  overview_html?: string | null;
  /**
   * Aboutページ用ヒーロー画像
   */
  hero_image?: (number | null) | Media;
  /**
   * テーマ語 (例: 万彩)
   */
  theme_word?: string | null;
  /**
   * テーマの説明文 (WYSIWYG)
   */
  theme_description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  theme_description_html?: string | null;
  /**
   * 会場名
   */
  venue_name?: string | null;
  /**
   * Google Maps 埋め込み URL
   */
  campus_map_url?: string | null;
  /**
   * お問い合わせフォーム URL
   */
  contact_form_url?: string | null;
  /**
   * テーマのメインビジュアル
   */
  theme_image?: (number | null) | Media;
  /**
   * HTMLのtitleタグ用
   */
  site_title?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page_home".
 */
export interface PageHome {
  id: number;
  /**
   * 開催前トップメッセージ
   */
  hero_message?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  hero_message_html?: string | null;
  /**
   * 複数ヒーロー画像
   */
  hero_images?: (number | Media)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "festival_meta_select".
 */
export interface FestivalMetaSelect<T extends boolean = true> {
  name?: T;
  event_days?: T;
  parking_map?: T;
  sns_links?: T;
  overview?: T;
  overview_html?: T;
  hero_image?: T;
  theme_word?: T;
  theme_description?: T;
  theme_description_html?: T;
  venue_name?: T;
  campus_map_url?: T;
  contact_form_url?: T;
  theme_image?: T;
  site_title?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page_home_select".
 */
export interface PageHomeSelect<T extends boolean = true> {
  hero_message?: T;
  hero_message_html?: T;
  hero_images?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}